""" Some special constant variables """

S_KILL = 0
S_WAKEUP = 1
S_SLEEP = 2
S_FREEZE = 3

B_HMIRROR = 1
B_VMIRROR = 2
B_TRANSLUCENT = 4
B_ABLEND = 8
B_SBLEND = 16
#B_NOCOLORKEY = 128

ALIGN_TOP_LEFT = 0
ALIGN_TOP = 1
ALIGN_TOP_RIGHT = 2
ALIGN_CENTER_LEFT = 3
ALIGN_CENTER = 4
ALIGN_CENTER_RIGHT = 5
ALIGN_BOTTOM_LEFT = 6
ALIGN_BOTTOM = 7
ALIGN_BOTTOM_RIGHT = 8     

C_SCREEN = 0
C_SCROLL = 1
C_M7 = 2 # LOL

SC_FOREHOR = 1
SC_FOREVER = 2
SC_BACKHOR = 4
SC_BACKVER = 8 